language: node_js

node_js:
  - "6"

install:
  - npm i

script:
  - npm run lint
  - npm run test

before_deploy:
  - npm version --no-git-tag-version $(git describe --tag)

deploy:
  provider: npm
  api_key: "$NPM_TOKEN"
  email: "$NPM_EMAIL"
  skip_cleanup: true
  on:
    tags: true
